#!/usr/bin/env python3
"""Generate editable streamable-http ``compose.dev.yml`` for the MCP connector fleet.

The central multiplexer proved an "edit locally, run in Docker" loop: instead of a
baked image, run ``python:3.11-slim``, bind-mount the connector's **source**, pip
install it at container start, and run its console script over streamable-http.
Code edits on the host go live on a container restart — no image rebuild, no
registry round-trip.

This generalizes that pattern. For every ``services/<name>-mcp`` whose source
exists at ``agent-packages/agents/<name>-mcp``, it emits a sibling
``compose.dev.yml`` derived from the production ``compose.yml`` — preserving
networks / dns / env / healthcheck / logging, swapping the image for the editable
runtime, and pinning the service to the node that holds the bind-mounted source.

    gen_editable_compose.py                       # generate for all source-backed connectors
    gen_editable_compose.py --only caddy-mcp,arr-mcp
    gen_editable_compose.py --server RW710 --workspace /home/apps/workspace
"""

from __future__ import annotations

import argparse
import os
import sys

import yaml

EDITABLE_IMAGE = "python:3.11-slim"


def _editable_command(orig_command, src="/src") -> list[str]:
    """Wrap the production command so the container installs the bind-mounted
    source first, then execs the original console script / args."""
    if isinstance(orig_command, str):
        run = orig_command
    elif isinstance(orig_command, list):
        run = " ".join(str(c) for c in orig_command)
    else:
        run = ""
    if not run:
        raise ValueError("service has no 'command' to wrap")
    return [
        "sh",
        "-c",
        f"pip install --no-cache-dir {src} && exec {run}",
    ]


def make_editable(compose: dict, name: str, source_path: str, server: str) -> dict:
    """Transform a production compose dict into its editable-dev variant."""
    services = compose.get("services", {})
    if name not in services:
        # single-service compose under a different key — take the only service.
        if len(services) != 1:
            raise ValueError(f"cannot locate the service for {name}")
        name = next(iter(services))
    svc = services[name]

    svc["image"] = EDITABLE_IMAGE
    svc["command"] = _editable_command(svc.get("command"))

    volumes = [v for v in svc.get("volumes", []) if ":/src:" not in str(v)]
    volumes.insert(0, f"{source_path}:/src:ro")
    svc["volumes"] = volumes

    # First boot pip-installs the package + deps — give the healthcheck room.
    hc = svc.get("healthcheck")
    if isinstance(hc, dict):
        hc["start_period"] = "90s"

    # Bind-mounted source lives on one node → the editable service must run there.
    deploy = svc.setdefault("deploy", {})
    deploy.setdefault("placement", {})["constraints"] = [
        f"node.labels.name == ${{SERVER:-{server}}}"
    ]
    return compose


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workspace", default=os.environ.get("WORKSPACE", "/home/apps/workspace"))
    ap.add_argument("--server", default="RW710", help="node label holding the source")
    ap.add_argument("--only", help="comma-separated subset of service names")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    services_dir = os.path.join(args.workspace, "services")
    source_root = os.path.join(args.workspace, "agent-packages", "agents")
    only = {s.strip() for s in (args.only or "").split(",") if s.strip()}

    generated, skipped = [], []
    for entry in sorted(os.listdir(services_dir)):
        if not entry.endswith("-mcp") or (only and entry not in only):
            continue
        compose_path = os.path.join(services_dir, entry, "compose.yml")
        source_path = os.path.join(source_root, entry)
        if not os.path.isfile(compose_path) or not os.path.isdir(source_path):
            skipped.append(entry)
            continue
        with open(compose_path) as f:
            compose = yaml.safe_load(f)
        try:
            editable = make_editable(compose, entry, source_path, args.server)
        except ValueError as e:
            skipped.append(f"{entry} ({e})")
            continue
        out = os.path.join(services_dir, entry, "compose.dev.yml")
        header = (
            "# EDITABLE-DEV variant (generated by gen_editable_compose.py).\n"
            "# Runs python:3.11-slim + bind-mounted source + runtime pip install;\n"
            "# edit the source on the host, restart this service, changes are live.\n"
            f"# Pinned to the node holding the source ({args.server}). Deploy as a\n"
            "# Portainer string-stack (or `docker stack deploy -c compose.dev.yml`).\n"
        )
        body = yaml.safe_dump(editable, sort_keys=False, default_flow_style=False)
        if args.dry_run:
            print(f"--- {out} ---\n{header}{body}")
        else:
            with open(out, "w") as f:
                f.write(header + body)
        generated.append(entry)

    print(f"generated {len(generated)} editable compose.dev.yml: {', '.join(generated)}")
    if skipped:
        print(f"skipped {len(skipped)} (no local source / not single-service): {', '.join(skipped[:40])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
