#!/usr/bin/env python3
"""Generate the genesis connector catalog from the canonical fleet registry.

Emits ``universal_skills/workflows/infra/agent-os-genesis/references/connector-catalog.md``
— one row per ``agents/*`` connector with its install/deploy facts, so the genesis
Step 0 questionnaire (deploy-container / deploy-baremetal / use-existing / skip) has a
single, non-drifting reference. Source of truth = agent-utilities
``deploy/mcp-fleet.registry.yml`` (package, console_script, image, profiles); per
connector we also surface the credential-ish env keys from its ``mcp_config.json``.

Run::

    python3 scripts/gen_connector_catalog.py \
        --registry ../../agent-utilities/deploy/mcp-fleet.registry.yml \
        --agents-dir ../../agents

Paths default to the standard agent-packages layout relative to this repo.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
OUT = (
    REPO
    / "universal_skills/workflows/infra/agent-os-genesis/references/connector-catalog.md"
)
# Default sibling-repo locations under agent-packages/ (this repo is
# agent-packages/skills/universal-skills, so siblings are two levels up).
_DEFAULT_REGISTRY = REPO / "../../agent-utilities/deploy/mcp-fleet.registry.yml"
_DEFAULT_AGENTS = REPO / "../../agents"

# Env keys that are credentials/endpoints worth surfacing (vs the noisy per-tool
# "*TOOL: True" flags and generic FASTMCP/TERM/NO_COLOR/AGENT_* scaffolding).
_SECRET_HINTS = (
    "TOKEN",
    "SECRET",
    "PASSWORD",
    "API_KEY",
    "APIKEY",
    "KEY",
    "URL",
    "DSN",
    "HOST",
)
_SKIP_EXACT = {"NO_COLOR", "TERM", "FASTMCP_LOG_LEVEL"}


def _secret_env_keys(agents_dir: Path, name: str) -> list[str]:
    cfg = agents_dir / name / "mcp_config.json"
    if not cfg.exists():
        return []
    try:
        data = json.loads(cfg.read_text())
    except Exception:
        return []
    keys: set[str] = set()
    for server in data.get("mcpServers", {}).values():
        for k in server.get("env") or {}:
            up = k.upper()
            if up in _SKIP_EXACT or up.endswith("TOOL") or up.startswith("AGENT_"):
                continue
            if any(h in up for h in _SECRET_HINTS):
                keys.add(k)
    return sorted(keys)


def generate(registry_path: Path, agents_dir: Path) -> str:
    reg = yaml.safe_load(registry_path.read_text())
    services = reg.get("services", [])
    lines = [
        "# Connector Catalog (generated)",
        "",
        "> Generated by `scripts/gen_connector_catalog.py` from the canonical fleet",
        "> registry (`agent-utilities/deploy/mcp-fleet.registry.yml`). Do not edit by",
        "> hand. One row per `agents/*` connector the genesis Step 0 questionnaire can",
        "> optionally install. **Install modes:** *bare-metal* = `uvx <script>` /",
        "> `uv tool install <package>`; *container* = pull the image and deploy it via",
        '> the chosen orchestrator (`CMD ["<script>"]`); *use-existing* / *skip* need',
        "> no install. Secrets are injected from OpenBao/Vault (or `.env`) at deploy —",
        "> never committed (see Step 8 `vault_sync`).",
        "",
        f"**{len(services)} connectors.**",
        "",
        "| Connector | Package | Bare-metal (uvx) | Container image | Profiles | Key secrets/env |",
        "|---|---|---|---|---|---|",
    ]
    for svc in sorted(services, key=lambda s: s.get("name", "")):
        name = svc.get("name", "")
        package = svc.get("package", name)
        script = svc.get("console_script", name)
        image = svc.get("image", "")
        profiles = ", ".join(svc.get("profiles", []) or [])
        secrets = _secret_env_keys(agents_dir, name)
        secrets_str = ", ".join(f"`{s}`" for s in secrets[:6]) or "—"
        if len(secrets) > 6:
            secrets_str += " …"
        lines.append(
            f"| `{name}` | `{package}` | `uvx {script}` | `{image}` | {profiles} | {secrets_str} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--registry", type=Path, default=_DEFAULT_REGISTRY)
    ap.add_argument("--agents-dir", type=Path, default=_DEFAULT_AGENTS)
    ap.add_argument("--check", action="store_true", help="fail if the catalog is stale")
    args = ap.parse_args()

    if not args.registry.exists():
        print(f"gen_connector_catalog: registry not found: {args.registry}")
        return 1
    content = generate(args.registry, args.agents_dir)
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current.strip() != content.strip():
            print("gen_connector_catalog: connector-catalog.md is stale — regenerate.")
            return 1
        print("gen_connector_catalog: catalog up to date.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"Wrote {OUT.relative_to(REPO)} ({len(content.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
