#!/usr/bin/env python3
"""GitHub write-helper for the two actions the github-mcp does NOT expose:
posting a comment and merging a PR. (Closing is done via the MCP —
`gith__update_issue` / `gith__update_pull_request` with state=closed — so this
helper deliberately does not implement close.)

Auth: reads the token from `~/.git-credentials` (the same credential the local
git push uses); override with the GITHUB_TOKEN env var. No token is ever printed.

SAFETY: both subcommands DRY-RUN by default and print what they would do. Nothing
is sent unless `--confirm` is passed. `merge` additionally refuses unless the
caller has already classified the PR safe_merge (the skill's job).

Usage:
  python gh_write.py comment <owner/repo> <number> --body "..." [--confirm]
  python gh_write.py merge   <owner/repo> <pr_number> [--method squash|merge|rebase] [--confirm]

Always prefix triage comments with the AI disclaimer (the skill enforces this):
  > *This was generated by AI during triage.*
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request


def _token() -> str:
    tok = os.environ.get("GITHUB_TOKEN")
    if tok:
        return tok
    path = os.path.expanduser("~/.git-credentials")
    try:
        with open(path) as fh:
            for line in fh:
                m = re.match(r"https://[^:]+:([^@]+)@github\.com", line.strip())
                if m:
                    return m.group(1)
    except OSError:
        pass
    sys.exit("No GitHub token (set GITHUB_TOKEN or populate ~/.git-credentials).")


def _api(method: str, path: str, payload: dict | None) -> tuple[int, dict]:
    req = urllib.request.Request(
        "https://api.github.com" + path,
        method=method,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={
            "Authorization": "token " + _token(),
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req) as r:
            body = r.read()
            return r.status, (json.loads(body) if body else {})
    except urllib.error.HTTPError as e:
        return e.code, {"error": e.read().decode()[:300]}


def cmd_comment(repo: str, number: int, body: str, confirm: bool) -> None:
    if not body.strip():
        sys.exit("refusing to post an empty comment")
    if not confirm:
        print(f"[dry-run] would comment on {repo}#{number}:\n---\n{body}\n---")
        print("(re-run with --confirm to post)")
        return
    st, resp = _api("POST", f"/repos/{repo}/issues/{number}/comments", {"body": body})
    print(f"comment -> HTTP {st}" + (f"  {resp.get('html_url','')}" if st < 300 else f"  {resp}"))


def cmd_merge(repo: str, number: int, method: str, confirm: bool) -> None:
    # re-check mergeability at the moment of merge (state can drift since triage)
    st, pr = _api("GET", f"/repos/{repo}/pulls/{number}", None)
    if st >= 300:
        sys.exit(f"could not load PR {repo}#{number}: HTTP {st}")
    ms = pr.get("mergeable_state")
    if pr.get("draft"):
        sys.exit(f"refusing: {repo}#{number} is a draft")
    if ms != "clean":
        sys.exit(f"refusing: {repo}#{number} mergeable_state={ms} (need 'clean')")
    if not confirm:
        print(f"[dry-run] would merge {repo}#{number} ({pr.get('title','')}) "
              f"via {method}; mergeable_state=clean")
        print("(re-run with --confirm to merge)")
        return
    st, resp = _api("PUT", f"/repos/{repo}/pulls/{number}/merge", {"merge_method": method})
    print(f"merge -> HTTP {st}" + (f"  sha={resp.get('sha','')}" if st < 300 else f"  {resp}"))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("comment")
    c.add_argument("repo"); c.add_argument("number", type=int)
    c.add_argument("--body", required=True); c.add_argument("--confirm", action="store_true")
    m = sub.add_parser("merge")
    m.add_argument("repo"); m.add_argument("number", type=int)
    m.add_argument("--method", choices=["squash", "merge", "rebase"], default="squash")
    m.add_argument("--confirm", action="store_true")
    args = ap.parse_args()
    if args.cmd == "comment":
        cmd_comment(args.repo, args.number, args.body, args.confirm)
    else:
        cmd_merge(args.repo, args.number, args.method, args.confirm)


if __name__ == "__main__":
    main()
